### ISSUE TITLE
Add a `dev` feature or similar instead of `debug_assertions`

### ISSUE THREAD

**Issue by benfrankel** [TheBevyFlock/bevy-template#18]
A few templates do this. Not 100% sure why. Maybe to allow dev tools to be compiled in / out for both debug and release builds, e.g. including web builds.

The feature can be named `dev`, `debug`, or something else. It should be a default feature so you can just do `cargo run`.

**Comment by benfrankel** [comment]
If this is added, existing references to `debug_assertions` should be updated.

**Comment by janhohenheim** [comment]
Reason to have this:
```toml
[features]
default = ["native_dev"]
native_dev = ["bevy/dynamic_linking", "dev"]
wasm_dev = ["dev"]
dev = [ "some", "other", "features" ]
```
